In [1]:
import os
import pandas as pd
import numpy as np

os.chdir('../DrugCell')

# Original Implementation

In [2]:
ls ./data/

SMILES_from_PubchemID.txt  nci60Act.csv
cell2ind.txt*              out.txt
cell2mutation.txt          out_.txt
drug2fingerprint.txt       pubchem_id.csv
drug2ind.txt*              pubchem_id_by_nsc.csv
drugcell_ont.txt           rcellminer_test.txt
drugcell_test.txt          sanger_cell_lines.txt
drugcell_train.txt         smiles_by_nsc.csv
drugcell_val.txt           test.csv
gene2ind.txt*              test.txt


In [3]:
!rm -rf Result_sample && mkdir Result_sample 
!rm -rf Hidden_sample/ && mkdir Hidden_sample

!python code/predict_drugcell_cpu.py \
            -gene2id data/gene2ind.txt \
            -cell2id data/cell2ind.txt \
            -drug2id data/drug2ind.txt \
            -genotype data/cell2mutation.txt \
            -fingerprint data/drug2fingerprint.txt \
            -hidden Hidden_sample \
            -result Result_sample \
            -load pretrained_model/drugcell_v1.pt \
            -predict data/rcellminer_test.txt

data/rcellminer_test.txt
Total number of cell lines = 1225
Total number of drugs = 684
printing drug features
[[0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
/Users/yoshitakainoue/code/graph_neural_network_drug_response/.venv/lib/python3.10/site-packages/torch/serialization.py:786: SourceChangeWarning: source code of class 'drugcell_NN.drugcell_nn' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/Users/yoshitakainoue/code/graph_neural_network_drug_response/.venv/lib/python3.10/site-packages/torch/serialization.py:786: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torc

In [4]:
!cat ./Result_sample/drugcell.predict

7.9301e-01
1.0002e+00
6.9300e-01
9.8586e-01
9.6704e-01
1.0227e+00
9.7536e-01
6.5597e-01
9.6661e-01
6.1569e-01
8.4432e-01
9.4538e-01
9.9546e-01
7.8992e-01
6.6365e-01
9.9421e-01
9.3813e-01
8.9996e-01
7.1678e-01
7.5820e-01
8.2878e-01
9.7734e-01
7.4013e-01
9.4540e-01
8.5440e-01
8.8130e-01
9.7873e-01
1.0195e+00
8.1896e-01
8.6380e-01
7.1268e-01
9.2435e-01
9.1836e-01
7.0084e-01
8.5131e-01
6.6365e-01
7.6670e-01
9.7709e-01
6.6941e-01
9.5611e-01
9.4432e-01
1.0127e+00
9.5257e-01
6.2871e-01
9.3144e-01
5.5870e-01
8.1940e-01
8.9561e-01
9.6895e-01
7.5146e-01
6.3211e-01
9.7633e-01
8.9329e-01
8.7380e-01
6.6921e-01
7.2408e-01
7.8543e-01
9.5338e-01
6.5982e-01
9.1514e-01
5.7111e-01
8.5446e-01
9.5220e-01
1.0091e+00
7.9356e-01
8.3328e-01
6.8765e-01
1.0214e+00
8.8802e-01
6.7582e-01
8.1695e-01
6.3211e-01
5.9171e-01
8.0784e-01
3.6838e-01
7.8281e-01
9.5809e-01
9.4271e-01
9.1426e-01
4.2979e-01
7.5555e-01
3.6958e-01
5.7974e-01
8.3567e-01
3.3931e-01
6.1704e-01
9.7972e-01
6.2456e-01
7.3893e-01
5.7232e-01
7.7046e-01

In [5]:
train = pd.read_csv('data/drugcell_train.txt', header=None, sep='\t')
rcellminer = pd.read_csv('data/rcellminer_test.txt', header=None, sep='\t')

In [6]:
train[1]

0                  C1CC(=O)NC(=O)C1N2C(=O)C3=CC=CC=C3C2=O
1       C1CN(CCN1)C(=O)C2=CC=C(C=C2)/C=C/C3=NNC4=CC=CC...
2       COC1=C(C=C2C(=C1)N=CN=C2NC3=CC(=C(C=C3)F)Cl)OC...
3          C1=CC=C2C(=C1)C3=CC=CC=C3N2CCC4=NC5=CC=CC=C5N4
4            CCCCCCCCCCC(C)(C)C(=O)NC1=C(C=C(C=C1OC)OC)OC
                              ...                        
9995    CNC(=O)C1=NC=CC(=C1)OC2=CC=C(C=C2)NC(=O)NC3=CC...
9996    C[C@]12CC[C@@]3(CCC(C[C@@H]3[C@@H]1C(=O)C=C4[C...
9997    CC1=NC=C(C=C1)OC2=C(C=C(C=C2)NC3=NC=NC4=C3C=C(...
9998    CCOC(=O)C1=C(SC2=C1CC(NC2(C)C)(C)C)NC(=O)C3=CC...
9999    C1=CN(C(=O)N=C1N)[C@H]2[C@H]([C@@H]([C@H](O2)C...
Name: 1, Length: 10000, dtype: object

In [7]:
rcellminer[1]

0       CN(CC1=CN=C2C(=N1)C(=NC(=N2)N)N)C3=CC=C(C=C3)C...
1                                 CCC(=O)OCN1C(=O)C=CC1=O
2       CC1=C(C(=O)C2=C(C1=O)N3C[C@H]4[C@@H]([C@@]3([C...
3       C1=CC(=CC=C1CC2=CC=C(C=C2)[As](=O)(O)O)[As](=O...
4       C1=CC=C2C=C3C(=CC2=C1)NC(=N3)CNC4=CC=C(C=C4)C(...
                              ...                        
1492    COC1=NC(=NC2=C1N=CN2[C@H]3[C@H]([C@@H]([C@H](O...
1493    CNC(=O)C1=CC=CC=C1SC2=CC3=C(C=C2)C(=NN3)/C=C/C...
1494    CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@](C3[...
1495    COC1=CC(=CC(=C1O)OC)[C@H]2[C@@H]3C(COC3=O)C(C4...
1496    CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@](C3[...
Name: 1, Length: 1497, dtype: object

In [8]:
set(train[1]) & set(rcellminer[1])

{'C1=C(SC(=C1)C2=CC=C(O2)C3=CC=C(S3)CO)CO',
 'C1=CC(=CC=C1CC2=CC=C(C=C2)[As](=O)(O)O)[As](=O)(O)O',
 'C1=CC=C(C(=C1)N)NC(=O)C2=CC=C(C=C2)CNC(=O)OCC3=CN=CC=C3',
 'C1=CC=C(C=C1)C2=CC=CC=C2NC(=O)CCCCCCCN3C=C(N=N3)C4=CN=CC=C4',
 'C1=CC=C(C=C1)COC2=NC(=NC3=C2NC=N3)N',
 'C1=CC=C(C=C1)NS(=O)(=O)C2=CC=CC(=C2)/C=C/C(=O)NO',
 'C1=CC=C2C(=C1)C(=O)C(=C(C2=O)SCCO)SCCO',
 'C1=CC=C2C(=C1)C3=NNC4=CC=CC(=C43)C2=O',
 'C1=CC=C2C=C3C(=CC2=C1)NC(=N3)CNC4=CC=C(C=C4)C(=O)O',
 'C1=CN(C(=O)N=C1N)[C@H]2C([C@@H]([C@H](O2)CO)O)(F)F',
 'C1CC1C(=O)N2CCN(CC2)C(=O)C3=C(C=CC(=C3)CC4=NNC(=O)C5=CC=CC=C54)F',
 'C1CN2CCC1C(=O)C2(CO)CO',
 'C1OC2=C(O1)C=C3C(=C2)C(=O)C=C(N3)C4=CC=CC=C4F',
 'CC(C)(CCC1=C2C(=C(C=C1)O)C(=O)C3=C(C4=C(C=C3O2)O[C@@H]5[C@]4(C=CO5)O)O)O',
 'CC1=C(C(=O)C2=C(C1=O)N3C[C@H]4[C@@H]([C@@]3([C@@H]2COC(=O)N)OC)N4)N',
 'CC1=C(C=C(C=C1)NC2=NC=CC(=N2)N(C)C3=CC4=NN(C(=C4C=C3)C)C)S(=O)(=O)N',
 'CC1=C(OC2=C1C3=CC=CC=C3C=C2)[N+](=O)[O-]',
 'CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@](C3[C@@H]([C@@](C2(C)C)(C[C@@H]1

In [9]:
!rm -rf Result_sample && mkdir Result_sample 
!rm -rf Hidden_sample/ && mkdir Hidden_sample

!python code/predict_drugcell_cpu.py \
            -gene2id data/gene2ind.txt \
            -cell2id data/cell2ind.txt \
            -drug2id data/drug2ind.txt \
            -genotype data/cell2mutation.txt \
            -fingerprint data/drug2fingerprint.txt \
            -hidden Hidden_sample \
            -result Result_sample \
            -load pretrained_model/drugcell_v1.pt \
            -predict data/out_.txt

data/out_.txt
Traceback (most recent call last):
  File "/Users/yoshitakainoue/code/graph_neural_network_drug_response/DrugCell/code/predict_drugcell_cpu.py", line 80, in <module>
    predict_data, cell2id_mapping, drug2id_mapping = prepare_predict_data(opt.predict, opt.cell2id, opt.drug2id)
  File "/Users/yoshitakainoue/code/graph_neural_network_drug_response/DrugCell/code/util.py", line 110, in prepare_predict_data
    test_feature, test_label = load_train_data(test_file, cell2id_mapping, drug2id_mapping)
  File "/Users/yoshitakainoue/code/graph_neural_network_drug_response/DrugCell/code/util.py", line 97, in load_train_data
    feature.append([cell2id[tokens[0]], drug2id[tokens[1]]])
KeyError: 'METHOTREXATE'


In [10]:
!cat data/drugcell_test.txt | head -n 5

LS123_LARGE_INTESTINE	CNC(=O)C1=NC=CC(=C1)OC2=CC(=C(C=C2)NC(=O)NC3=CC(=C(C=C3)Cl)C(F)(F)F)F	0.8942239155087995
RT4_URINARY_TRACT	C[C@@H](C(=O)N[C@H]1C2=CC=CC=C2CCN(C1=O)C)NC(=O)[C@H](C(C)C)O	0.8742612017769524
SCABER_URINARY_TRACT	C1CCN(C1)C(=O)NC2=CC=CC(=C2)NC3=NC=C(C(=N3)NCCC4=CN=CN4)Br	0.9600720748580642
TE617T_SOFT_TISSUE	C1CN(CCC12C(=O)NCN2C3=CC=CC=C3)CCNC(=O)C4=CC5=CC=CC=C5C=C4	0.9873540669080934
MOGGCCM_CENTRAL_NERVOUS_SYSTEM	CC1=CN=C(N=C1NC2=CC(=CC=C2)S(=O)(=O)NC(C)(C)C)NC3=CC=C(C=C3)OCCN4CCCC4	0.8719973751110028


In [11]:
!cat data/out_.txt | head -n 5

METHOTREXATE	CN(Cc1cnc2nc(N)nc(N)c2n1)c3ccc(cc3)C(=O)N[C@@H](CCC(=O)O)C(=O)O
6-THIOGUANINE	NC1=NC(=S)c2[nH]cnc2N1
6-MERCAPTOPURINE	S=C1N=CNc2nc[nH]c12
Allopurinol	O=C1NC=Nc2[nH]ncc12
Chlorambucil	OC(=O)CCCc1ccc(cc1)N(CCCl)CCCl


In [12]:
os.chdir('/home/inoue019/code/DrugCell/code')

FileNotFoundError: [Errno 2] No such file or directory: '/home/inoue019/code/DrugCell/code'

# module for python script

In [ ]:
from drugcell_prediction import predict_dcell

In [ ]:
!rm -rf Result_sample && mkdir Result_sample 
!rm -rf Hidden_sample/ && mkdir Hidden_sample

predict_dcell(
    '../data/drugcell_test.txt',
    '../data/cell2ind.txt',
    '../data/drug2ind.txt',
    '../data/cell2mutation.txt',
    '../data/drug2fingerprint.txt',
    '../pretrained_model/drugcell_v1.pt',
    'Hidden_sample',
    'Result_sample'
)