In [1]:
import os
import pandas as pd
import numpy as np

os.chdir('../DrugCell')

# Original Test Data

In [6]:
!rm -rf Result_sample && mkdir Result_sample 
!rm -rf Hidden_sample/ && mkdir Hidden_sample

!python code/predict_drugcell_cpu.py \
            -gene2id data/gene2ind.txt \
            -cell2id data/cell2ind.txt \
            -drug2id data/drug2ind.txt \
            -genotype data/cell2mutation.txt \
            -fingerprint data/drug2fingerprint.txt \
            -hidden Hidden_sample \
            -result Result_sample \
            -load pretrained_model/drugcell_v1.pt \
            -predict data/drugcell_test.txt

Total number of cell lines = 1225
Total number of drugs = 684
printing drug features
[[0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
/Users/yoshitakainoue/code/graph_neural_network_drug_response/.venv/lib/python3.9/site-packages/torch/serialization.py:786: SourceChangeWarning: source code of class 'drugcell_NN.drugcell_nn' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/Users/yoshitakainoue/code/graph_neural_network_drug_response/.venv/lib/python3.9/site-packages/torch/serialization.py:786: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = 

# rcellminer data

In [4]:
!rm -rf Result_sample && mkdir Result_sample 
!rm -rf Hidden_sample/ && mkdir Hidden_sample

!python code/predict_drugcell_cpu.py \
            -gene2id data/gene2ind.txt \
            -cell2id data/cell2ind.txt \
            -drug2id data/drug2ind.txt \
            -genotype data/cell2mutation.txt \
            -fingerprint data/drug2fingerprint.txt \
            -hidden Hidden_sample \
            -result Result_sample \
            -load pretrained_model/drugcell_v1.pt \
            -predict data/rcellminer_test.txt

Total number of cell lines = 1225
Total number of drugs = 684
printing drug features
[[0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
/Users/yoshitakainoue/code/graph_neural_network_drug_response/.venv/lib/python3.9/site-packages/torch/serialization.py:786: SourceChangeWarning: source code of class 'drugcell_NN.drugcell_nn' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/Users/yoshitakainoue/code/graph_neural_network_drug_response/.venv/lib/python3.9/site-packages/torch/serialization.py:786: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = 

# rcellminer data without negative value

In [5]:
!rm -rf Result_sample && mkdir Result_sample 
!rm -rf Hidden_sample/ && mkdir Hidden_sample

!python code/predict_drugcell_cpu.py \
            -gene2id data/gene2ind.txt \
            -cell2id data/cell2ind.txt \
            -drug2id data/drug2ind.txt \
            -genotype data/cell2mutation.txt \
            -fingerprint data/drug2fingerprint.txt \
            -hidden Hidden_sample \
            -result Result_sample \
            -load pretrained_model/drugcell_v1.pt \
            -predict data/rcellminer_test_remove_negative_values.txt

Total number of cell lines = 1225
Total number of drugs = 684
printing drug features
[[0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
/Users/yoshitakainoue/code/graph_neural_network_drug_response/.venv/lib/python3.9/site-packages/torch/serialization.py:786: SourceChangeWarning: source code of class 'drugcell_NN.drugcell_nn' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = True` and use the patch tool to revert the changes.
  warnings.warn(msg, SourceChangeWarning)
/Users/yoshitakainoue/code/graph_neural_network_drug_response/.venv/lib/python3.9/site-packages/torch/serialization.py:786: SourceChangeWarning: source code of class 'torch.nn.modules.linear.Linear' has changed. you can retrieve the original source code by accessing the object's source attribute or set `torch.nn.Module.dump_patches = 

# module for python script

In [ ]:
from drugcell_prediction import predict_dcell

In [ ]:
!rm -rf Result_sample && mkdir Result_sample 
!rm -rf Hidden_sample/ && mkdir Hidden_sample

predict_dcell(
    '../data/drugcell_test.txt',
    '../data/cell2ind.txt',
    '../data/drug2ind.txt',
    '../data/cell2mutation.txt',
    '../data/drug2fingerprint.txt',
    '../pretrained_model/drugcell_v1.pt',
    'Hidden_sample',
    'Result_sample'
)