In [1]:
import os
import pandas as pd
import numpy as np

os.chdir('../DrugCell')

# rcellminer data

In [2]:
!rm -rf Result_sample && mkdir Result_sample 
!rm -rf Hidden_sample/ && mkdir Hidden_sample

!python code/predict_drugcell_cpu.py \
            -gene2id data/gene2ind.txt \
            -cell2id data/cell2ind.txt \
            -drug2id data/drug2ind.txt \
            -genotype data/cell2mutation.txt \
            -fingerprint data/drug2fingerprint.txt \
            -hidden Hidden_sample \
            -result Result_sample \
            -load pretrained_model/model_40.pt \
            -predict ../data/test.txt

Total number of cell lines = 1225
Total number of drugs = 684
printing drug features
[[0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Test pearson corr	GO:0008150	0.288012


In [3]:
res = pd.read_csv(
    'Result_sample/drugcell.predict', 
    header=None
)

test = pd.read_csv(
    '../data/test.txt',
    header=None,
    sep='\t'
)[[2, 0, 1]]

In [4]:
pd.concat(
    [res, test],
    axis=1
)

0         2                                         0  \
0    0.095920 -0.250324                              OVCAR8_OVARY   
1    0.371440  0.328217                               SKMEL5_SKIN   
2    0.311890  0.492828                              NCIH460_LUNG   
3   -0.030919  0.646984              SF295_CENTRAL_NERVOUS_SYSTEM   
4    0.313700  0.133631                             HS578T_BREAST   
..        ...       ...                                       ...   
294 -0.448950 -0.253696                               SKMEL2_SKIN   
295 -0.412110 -0.350329                              PC3_PROSTATE   
296  0.370890  0.460247                     SW620_LARGE_INTESTINE   
297  0.352110  0.308771  SR786_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE   
298  0.391030  1.176457                              CAKI1_KIDNEY   

                                                     1  
0    CNC(=O)C1=CC=CC=C1SC2=CC3=C(C=C2)C(=NN3)/C=C/C...  
1    CC1=CC=C(C=C1)S(=O)(=O)OCC(=O)NC2=CC(=C(C=C2)C...  
2                    CCCCC1=CC2=C(C=C1)N=C(N2)NC(=O)OC  
3                    CCCCC1=CC2=C(C=C1)N=C(N2)NC(=O)OC  
4    C[C@H]1CCC[C@@]2([C@@H](O2)C[C@H](OC(=O)C[C@@H...  
..                                                 ...  
294                            CCC(=O)OCN1C(=O)C=CC1=O  
295  CCN(CC)CCNC(=O)C1=C(NC(=C1C)/C=C\2/C3=C(C=CC(=...  
296  CC1=C2[C@H](C(=O)[C@@]3([C@H](C[C@@H]4[C@]([C@...  
297  C1=CN(C(=O)N=C1N)[C@H]2C([C@@H]([C@H](O2)CO)O)...  
298  CS(=O)(=O)CCNCC1=CC=C(O1)C2=CC3=C(C=C2)N=CN=C3...  

[299 rows x 4 columns]