In [8]:
import os
import pandas as pd
import numpy as np
from sklearn.metrics import mean_squared_error as mse

os.chdir('../DrugCell')

# rcellminer data

In [9]:
!rm -rf Result_sample && mkdir Result_sample 
!rm -rf Hidden_sample/ && mkdir Hidden_sample

!python code/predict_drugcell_cpu.py \
            -gene2id data/gene2ind.txt \
            -cell2id data/cell2ind.txt \
            -drug2id data/drug2ind.txt \
            -genotype data/cell2mutation.txt \
            -fingerprint data/drug2fingerprint.txt \
            -hidden Hidden_sample \
            -result Result_sample \
            -load pretrained_model/model_32.pt \
            -predict ../data/test.txt

Total number of cell lines = 1225
Total number of drugs = 684
printing drug features
[[0. 1. 1. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Test pearson corr	GO:0008150	0.201491


In [10]:
res = pd.read_csv(
    'Result_sample/drugcell.predict', 
    header=None
)

test = pd.read_csv(
    '../data/test.txt',
    header=None,
    sep='\t'
)[[2, 0, 1]]

In [11]:
t = pd.concat(
    [res, test],
    axis=1
)
t.columns = ['pred', 'true', 'Cell line', 'SMILES']

In [12]:
print(t.to_markdown())

|     |       pred |         true | Cell line                                   | SMILES                                                                                                                                                                    |
|----:|-----------:|-------------:|:--------------------------------------------|:--------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|   0 | -0.062706  | -1.21742     | K562_HAEMATOPOIETIC_AND_LYMPHOID_TISSUE     | C1=CC=C2C(=C1)C3=NNC4=CC=CC(=C43)C2=O                                                                                                                                     |
|   1 | -0.16895   |  0.56016     | M14_SKIN                                    | CCCCC1=CC2=C(C=C1)N=C(N2)NC(=O)OC                                                                                                                           

In [13]:
np.corrcoef(t.pred, t.true)

array([[1.        , 0.20149209],
       [0.20149209, 1.        ]])

In [14]:
mse(t.pred, t.true)

1.064236592262479